name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' # use the version of Node.js your project needs

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --if-present
